---
- name: "Set the number of retry loop to 0 as waiting not requested"
  set_fact:
    entitlement_retries: 0
  when: entitlement_test_and_wait != 'yes'

- name: "Set the number of retry loop to {{ entitlement_nb_wait_retries }} as waiting is requested"
  set_fact:
    entitlement_retries: "{{ entitlement_nb_wait_retries }}"
  when: entitlement_test_and_wait == 'yes'

- block:
  - name: Wait for the entitlement Pod to succeed
    shell: |
      set -o errexit;
      oc delete -f "{{ entitlement_test_pod }}" --ignore-not-found=true;
      oc create -f "{{ entitlement_test_pod }}";
      i=0;
      CMD="oc get pod/entitlement-tester
                -o custom-columns=:.status.phase
                --no-headers
                -n default
                ";
      while ! $CMD | egrep 'Succeeded|Error|Failed'; do
          echo "Waiting for Pod completion ... (#${i})";
          sleep 10;
          i=$(($i+1));
          if [[ "$i" == "12" ]]; then
            echo "Pod took too long to terminate, aborting..."
            exit 1;
          fi;
      done;
      $CMD;
      $CMD | egrep 'Succeeded';
    register: entitlement_wait
    until: entitlement_wait.rc == 0
    retries: "{{ entitlement_retries}}"
    delay: 30

  rescue:
  - include_role:
      name: entitlement_inspect
    vars:
      _entitlement_inspect_called_from_testwait: "yes"
    when: entitlement_inspect_on_failure == 'yes'

  - fail:
      msg: Failed because the entitlement Pod did not succeed.

  always:
  - name: Get the test Pod logs
    command: oc logs pod/entitlement-tester -n default
    when: _entitlement_testwait_called_from_inspect == "yes" or entitlement_wait.rc != 0

  - name: Delete the test Pod
    command: oc delete -f "{{ entitlement_test_pod }}"
