---
# path to the file to use a repo list in the Driver container
gpu_operator_set_repo_filename: ""


# path where the repo file will be stored in the driver container
gpu_operator_set_repo_destdir: "/etc/distro.repos.d"
