---
# wait for the successfull deployment of the entitlement?
entitlement_test_and_wait: 'no'

# the number of retries to perform when waiting for the entitlement
entitlement_nb_wait_retries: 20

entitlement_inspect_on_failure: "yes"
# ---
_entitlement_testwait_called_from_inspect: "no"
# ---
entitlement_test_pod: 'roles/entitlement_test_wait/files/test_pod.yml'
