apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  label:
    profile: sshless
  name: hello-world
spec:
  sshAuthMountPath: /home/mpi/.ssh
  cleanPodPolicy: Running
  slotsPerWorker: 1
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - name: mpi-launcher
            command:
            - mpirun
            - -np
            - "2"
            - -bind-to
            - nonem
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - echo Hello World from $(cat /proc/sys/kernel/hostname)
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base-python
            imagePullPolicy: Always
            env:
            - name: OMPI_MCA_plm_rsh_agent
              value: "bash /mnt/sshless-scripts/connect.sh"
            - name: SSHLESS_SECRET_PATH
              value: "/mnt/sshless-secret"
            volumeMounts:
            - mountPath: /mnt/sshless-scripts
              name: sshless-scripts
            - mountPath: /mnt/sshless-secret
              name: sshless-secret
          volumes:
          - name: sshless-scripts
            configMap:
              defaultMode: 0777
              name: sshless-scripts
          - name: sshless-secret
            secret:
              secretName: sshless-secret
    Worker:
      replicas: 2
      template:
        metadata:
          labels:
            app: mpi-app
        spec:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: mpi-app
          containers:
          - name: mpi-worker
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base-python
            imagePullPolicy: Always
            env:
            - name: OMPI_MCA_plm_rsh_agent
              value: "bash /mnt/sshless-scripts/connect.sh"
            - name: SSHLESS_SECRET_PATH
              value: "/mnt/sshless-secret"
            command:
            - python3
            - /mnt/sshless-scripts/server.py
            volumeMounts:
            - mountPath: /mnt/sshless-scripts
              name: sshless-scripts
            - mountPath: /mnt/sshless-secret
              name: sshless-secret
          volumes:
          - name: sshless-scripts
            configMap:
              defaultMode: 0777
              name: sshless-scripts
          - name: sshless-secret
            secret:
              secretName: sshless-secret
