---
# deploy the entitlement on the cluster?
entitlement_deploy: 'yes'
# undeploy the entitlement on the cluster?
entitlement_undeploy: 'no'
# path to the pre-prepared yaml resources of the entitlement
entitlement_resources: ''
# path to the PEM file of the entitlement
entitlement_pem: ''
# path to the RHSM file of the entitlement
entitlement_rhsm: 'roles/entitlement/files/rhsm.conf'

# test the successfull deployment of the entitlement?
entitlement_test: 'yes'
# wait for the successfull deployment of the entitlement?
entitlement_test_wait: 'yes'

# gather information about entitlement deployment
# (done anyway in case of test failure)
entitlement_inspect: 'no'

# template files for the MachineConfig resources
entitlement_mc_rhsm: 'roles/entitlement/files/mc_rhsm.yml'
entitlement_mc_pem: 'roles/entitlement/files/mc_pem.yml'
entitlement_py_apply: 'roles/entitlement/files/apply_template.py'
entitlement_test_pod: 'roles/entitlement/files/test_pod.yml'

# the number of retries to perform when waiting for the entitlement
nb_entitlement_wait_retries: 20
