---
- block:
  - name: "Deploy entitlement from resource file '{{ entitlement_resources }}'"
    command: oc create -f "{{ entitlement_resources }}"
  - name: Entitlement is already deployed, end the play
    # Warning: this will prevent using multiple roles side by side ...
    meta: end_play
  when: entitlement_resources | default('', true) | trim != ''

- block:
  - name: "Deploy RHSM from file '{{ entitlement_rhsm }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
        "{{ entitlement_mc_rhsm }}" BASE64_ENCODED_RHSM_FILE "{{ entitlement_rhsm }}"
      | oc apply -f-
  when: entitlement_rhsm | default('', true) | trim != ''

- block:
  - name: "Deploy the pem and key-pem from file '{{ entitlement_pem }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
        "{{ entitlement_mc_pem }}" BASE64_ENCODED_PEM_FILE "{{ entitlement_pem }}"
      | oc apply -f-
  when: entitlement_pem | default('', true) | trim != ''

- block:
  - name: "Deploy the repo CA from file '{{ entitlement_mc_rhsm_ca }}'"
    shell:
      set -o pipefail;
      python3 "{{ entitlement_py_apply }}"
        "{{ entitlement_mc_rhsm_ca }}" BASE64_ENCODED_RHSM_CA_FILE "{{ entitlement_repo_ca }}"
      | oc apply -f-
  when: entitlement_repo_ca | default('', true) | trim != ''
