---
- name: Check that nfd_operator_image_tag is defined
  fail: msg="Bailing out. This play requires 'nfd_operator_image_tag'"
  when: nfd_operator_image_tag is undefined

- name: Check that nfd_git_repo is defined
  fail: msg="Bailing out. This play requires 'nfd_git_repo'"
  when: nfd_operator_git_repo is undefined

- name: Build nfd from master
  include_tasks: build.yml

- name: Deploy nfd from master
  include_tasks: deploy.yml
