- name: Create the namespace for the NFD Operator
  command: oc apply -f "{{ nfd_operator_namespace }}"

- name: Create the OperatorGroup object
  command: oc apply -f "{{ nfd_operator_operatorgroup }}"

- name: "Create the OperatorHub subscription for the NFD Operator (nfd_channel = {{ nfd_channel }})"
  shell:
    set -o pipefail;
    sed 's|{{ '{{' }} nfd_channel {{ '}}' }}|{{ nfd_channel }}|' "{{ nfd_operator_operatorhub_sub }}"
      | oc apply -f-
  args:
    warn: false # don't warn about using sed here

- name: Create the NodeFeatureDiscovery CR for the NFD Operator
  block:
    - name: Apply NodeFeatureDiscovery manifest
      command: oc apply -f "{{ nfd_operator_cr }}"
      register: apply_nfd_cr
      until: apply_nfd_cr.rc != 1
      retries: 20
      delay: 15
  rescue:
    - name: List the NFD subscription (debug)
      command: oc get subscriptions -n openshift-nfd
      failed_when: false

    - name: Describe the NFD subscription (debug)
      command: oc describe subscriptions/nfd -n openshift-nfd
      failed_when: false

    - name: List the ClusterServiceVersion status (debug)
      command: oc get ClusterServiceVersion -n openshift-nfd
      failed_when: false

    - name: Describe the ClusterServiceVersion status (debug)
      command: oc describe ClusterServiceVersion -n openshift-nfd
      failed_when: false

    - name: Failed when creating the NFD NodeFeatureDiscovery CR
      fail:
        msg: "{{ apply_nfd_cr }}"
