---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mpi-python-base-image
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mpi:base-python
  source:
    dockerfile: |2
      FROM mpi:base

      RUN dnf --quiet -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
       && dnf install --quiet -y python3 python3-pynacl python3-gssapi \
       && dnf install --quiet -y openssl \
       && pip3 install --upgrade pip \
       && pip3 install setuptools-rust paramiko

    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: mpi:base
    type: Docker
  triggers:
  - type: ConfigChange
