---
- name: find a node with our tuned label
  command: oc get nodes -l "{{ tuned_module_fuse_label }}" -oname
  register: fuse_nodes
- name: find a worker node to label for loading tuned module
  shell: oc get nodes -l node-role.kubernetes.io/worker -oname | head -1
  when: fuse_nodes.stdout == ""
  register: worker_nodes
- name: mark node with our tuned label
  command: oc label "{{ worker_nodes.stdout }}" "{{ tuned_module_fuse_label }}="
  when: fuse_nodes.stdout == ""

- name: apply tuned fuse profile manifest
  command: oc apply -f "{{ tuned_module_fuse }}"

- name: apply ci utils manifest
  command: oc apply -f "{{ gpu_operator_ci_utils }}"

- name: authorize ns/gpu-operator-ci Pods to access ns/gpu-operator-ci-utils images
  command: oc policy add-role-to-user \
             system:image-puller system:serviceaccount:gpu-operator-ci:default \
             --namespace=gpu-operator-ci-utils

- name: apply namespace manifest
  command: oc apply -f "{{ gpu_operator_namespace }}"

- name: apply imagestream manifest
  command: oc apply -f "{{ gpu_operator_imagestream }}"

- name: apply image helper builder manifest
  command: oc apply -f "{{ gpu_operator_helper_image_builder }}"

- name: wait for the helper image to be built
  block:
  - name: wait for the helper image to be built
    shell: oc get pod --field-selector=status.phase=Succeeded,metadata.name=helper-image-builder-1-build --no-headers -oname -n gpu-operator-ci-utils | grep helper-image-builder-1-build
    register: wait_helper_image
    until: wait_helper_image.rc != 1
    retries: 40
    delay: 30
  rescue:
  - name: get info about helper image build failure
    command: oc get pods -n gpu-operator-ci
    ignore_errors: true
  - name: get logs of helper image build failure
    command: oc get logs bc/helper-image-builder -n gpu-operator-ci
    ignore_errors: true
  - name: get info about helper image build failure
    command: oc describe build/helper-image-builder-1 -n gpu-operator-ci
  - name: operator image failed to build
    fail:
      msg: operator image failed to build

- name: apply operator image builder script manifest
  command: oc apply -f "{{ gpu_operator_image_builder_script }}"

- name: find the name of the builder-dockercfg secret
  block:
    - name: find the name of the builder-dockercfg secret
      shell: oc get secrets -oname -n gpu-operator-ci | cut -d/ -f2 | grep builder-dockercfg
      register: builder_secret
  rescue:
    - name: Failed to find the builder-dockercfg secret
      fail:
        msg: "No builder-dockercfg secret in the 'gpu-operator-ci' namespace ..."

- name: delete operator image builder pod, if any
  shell: oc delete -f "{{ gpu_operator_image_builder_pod }}" || true

- name: delete operator image, if any
  shell: oc delete imagestreamtag/gpu-operator-ci:gpu-operator -n gpu-operator-ci || true

- name: apply operator image builder pod manifest
  shell: sed 's|{{ '{{' }} builder_secret {{ '}}' }}|{{ builder_secret.stdout }}|' "{{ gpu_operator_image_builder_pod }}" \
       | sed 's|{{ '{{' }} gpu_operator_git_repo {{ '}}' }}|{{ gpu_operator_git_repo }}|' \
       | sed 's|{{ '{{' }} gpu_operator_git_ref {{ '}}' }}|{{ gpu_operator_git_ref }}|' \
       | sed 's|{{ '{{' }} gpu_operator_image_tag {{ '}}' }}|{{ gpu_operator_image_tag }}|' \
       | oc apply -f-
  args:
    warn: false # don't warn about using sed here

- name: wait for the operator image to be built
  block:
  - name: wait for the operator image to be built
    shell: oc get pod --field-selector=status.phase=Succeeded,metadata.name=operator-image-builder-pod --no-headers -oname -n gpu-operator-ci | grep operator-image-builder-pod
    register: wait_image_builder_pod
    until: wait_image_builder_pod.rc != 1
    retries: 40
    delay: 30
  rescue:
  - name: get info about operator image build failure
    command: oc get pods -n gpu-operator-ci
    ignore_errors: true
  - name: get logs of image build failure
    command: oc get logs pod/operator-image-builder-pod
    ignore_errors: true
  - name: operator image failed to build
    fail:
      msg: operator image failed to build
