- name: Remove custom node label for tune
  block:
    - name: find a node with our tuned label
      shell: oc get nodes -l "{{ tuned_module_fuse_label }}" -oname | head -1
      register: fuse_node
    - name: remove our tuned label on the node
      command: oc label "{{ fuse_node.stdout }}" "{{ tuned_module_fuse_label }}-"
  rescue:
    - debug:
        msg: "No node with our tuned label"

- name: delete tuned fuse profile # in the openshift-cluster-node-tuning-operator namespace
  command: oc delete -f "{{ tuned_module_fuse }}" --ignore-not-found=true

- name: delete namespace and everything it contains
  command: oc delete -f "{{ gpu_operator_namespace }}" --ignore-not-found=true

- name: delete utils namespace and everything it contains
  command: oc delete -f "{{ gpu_operator_ci_utils }}" --ignore-not-found=true

- name: delete GPU Operator CRD
  command: oc delete crd clusterpolicies.nvidia.com --ignore-not-found=true
