- name: delete possible stalled GPU-operator resources from failed undeployment
  shell: |
    oc delete --ignore-not-found=true ServiceAccount/gpu-operator -n gpu-operator;
    oc delete --ignore-not-found=true ClusterRole/gpu-operator;
    oc delete --ignore-not-found=true ClusterRoleBinding/gpu-operator;
    oc delete --ignore-not-found=true ClusterPolicy cluster-policy;
    oc delete --ignore-not-found=true SecurityContextConstraints restricted-readonly;
    oc delete --ignore-not-found=true Namespace/gpu-operator-resources;

- block:
  - name: deploy the custom version of the GPU operator
    command: bash "{{ gpu_operator_helm_install }}" deploy_from_commit "{{ gpu_operator_git_repo }}" "{{ gpu_operator_git_ref }}" "{{ gpu_operator_image_tag }}"

  rescue:
  - name: get the state of the GPU operator pod (debug)
    command: oc get pods -n gpu-operator-ci
  - name: get the logs of the GPU operator pod (debug)
    command:
      oc logs -n gpu-operator-ci deployment.apps/gpu-operator
  - name: fail because of a previous error
    fail:
      msg: failing because of a previous error
