- name: delete possible stalled GPU-operator resources from failed undeployment
  shell: |
    oc delete --ignore-not-found=true ServiceAccount/gpu-operator -n gpu-operator;
    oc delete --ignore-not-found=true ClusterRole/gpu-operator;
    oc delete --ignore-not-found=true ClusterRoleBinding/gpu-operator;
    oc delete --ignore-not-found=true ClusterPolicy cluster-policy;
    oc delete --ignore-not-found=true SecurityContextConstraints restricted-readonly;
    oc delete --ignore-not-found=true Namespace/gpu-operator-resources;

- name: deploy the custom version of the GPU operator
  command: bash "{{ gpu_operator_helm_install }}" deploy_from_commit "{{ gpu_operator_git_repo }}" "{{ gpu_operator_git_ref }}" "{{ gpu_operator_image_tag }}"
