---
- name: Check that gpu_operator_image_tag_uid is defined
  fail: msg="Bailing out. This play requires 'gpu_operator_image_tag_uid'"
  when: gpu_operator_image_tag_uid is undefined

- name: Check that gpu_operator_git_repo is defined
  fail: msg="Bailing out. This play requires 'gpu_operator_git_repo'"
  when: gpu_operator_git_repo is undefined

- name: Check that gpu_operator_git_ref is defined
  fail: msg="Bailing out. This play requires 'gpu_operator_git_ref'"
  when: gpu_operator_git_ref is undefined

- block:
  - name: Install NFD-operator from OperatorHub
    include_role:
      name: nv_gpu
      tasks_from: install_nfd
    when: install_nfd_operator_from_hub == "yes"

  - name: Build GPU-operator from custom commit
    import_tasks: roles/nv_gpu_install_from_commit/tasks/build.yml
    when: install_gpu_operator_from_commit == "yes"

  - name: Deploy GPU-operator from custom commit with helm
    import_tasks: roles/nv_gpu_install_from_commit/tasks/deploy.yml
    when: install_gpu_operator_from_commit == "yes"

  - include_tasks: roles/nv_gpu/tasks/ci_checks.yml
    when: user_mode == 'ci'
  rescue:
  - name: Verbose Failure
    include_role:
      name: nv_gpu
      tasks_from: verbose_failure
  - name: Failing because of a previous error
    fail:
      msg: "Failing because of a previous error"
  always:
    - name: Undeploy GPU-operator from custom commit with helm
      import_tasks: roles/nv_gpu_install_from_commit/tasks/undeploy.yml
      when: undeploy_gpu_operator == 'yes'

    - name: Cleanup custom commit resources
      import_tasks: roles/nv_gpu_install_from_commit/tasks/cleanup.yml
      when: undeploy_gpu_operator == 'yes'
