- name: Wait for the GPU Operator OperatorHub ClusterServiceVersion name
  command:
    oc get ClusterServiceVersion
       -l operators.coreos.com/gpu-operator-certified.openshift-operators
       -oname
       -n openshift-operators
  register: gpu_operator_csv_name_cmd
  failed_when: not gpu_operator_csv_name_cmd.stdout
  retries: 15
  delay: 30

- name: Get the clusterpolicy of the GPU Operator from OperatorHub CSV
  shell:
    set -o pipefail;
    oc get "{{ gpu_operator_csv_name_cmd.stdout }}"
       -n openshift-operators
       -ojson
    | jq -r '.metadata.annotations."alm-examples"'
    | jq .[0] > "{{ artifact_extra_logs_dir }}/gpu_operator_clusterpolicy.json"
  register: operatorhub_clusterpolicy
  until: operatorhub_clusterpolicy.rc == 0
  retries: 20
  delay: 15

- block:
  - name: Create the clusterPolicy CR for the GPU Operator
    command: oc apply -f "{{ artifact_extra_logs_dir }}/gpu_operator_clusterpolicy.json"
    register: test_clusterpolicy_cr
    until: test_clusterpolicy_cr.rc != 1
    retries: 20
    delay: 15

  rescue:
  - name: Inspect the Subscriptions status (debug)
    shell:
      (oc get subscriptions -n openshift-operators &&
       oc describe subscriptions/gpu-operator-certified -n openshift-operators)
       > {{ artifact_extra_logs_dir }}/gpu_operator_Subscription.log
    failed_when: false

  - name: Get the ClusterServiceVersion status (debug)
    shell:
      (oc get ClusterServiceVersion -A &&
       oc describe "{{ gpu_operator_csv_name_cmd.stdout }}" -n openshift-operators)
       > {{ artifact_extra_logs_dir }}/gpu_operator_ClusterServiceVersion.log
    failed_when: false

  - name: Failing because the ClusterPolicy CR cannot be created
    fail: msg="Failed because the ClusterPolicy CR cannot be created"
