---
- name: Check for 'oc'
  command: >
    type -a oc

- name: Check for 'jq', needed for parsing and debugging oc outputs
  command: >
    type -a jq
  register: jq_cli
  ignore_errors: true

- name: Get the KUBECONFIG value
  shell: echo $KUBECONFIG
  register: kubeconfig_value

- name: check if the kubeconfig file exists
  stat:
    path: "{{ kubeconfig_value.stdout }}"
  register: kubeconfig_file

- name: Verify that KUBECONFIG file exists
  fail:
    msg: "Kubeconfig not found at {{ kubeconfig.stdout }}"
  when: kubeconfig_file.stat.exists != true

- name: Get oc user
  command: >
    oc whoami

- name: Get oc version
  command: >
    oc version
