---
- name: Capture OpenShift version (debug)
  command: oc version

- name: Fetch 'openshift_release' value and check dependencies
  shell:
    oc version -o json
    | jq --raw-output '.openshiftVersion'
    | cut -b-3
  register: ocp_version
  # Abort the play if anything goes wrong:
  # - KUBECONFIG not valid
  # - cannot join the server
  # - oc or jq missing
  failed_when: ocp_version.stdout == 'nul' or ocp_version.stdout == ""

- name: 'Store openshift_release={{ ocp_version.stdout }}'
  set_fact:
    openshift_release: "{{ ocp_version.stdout }}"
  when: openshift_release | default('', true) | trim == ''
