---
- block:
  - name: Fetch 'openshift_release' value and check dependencies
    # see the 'fail' message below before modifying this command,
    # it verifies that the main dependencies are met.
    shell:
      oc version -o json
      | jq --raw-output '.openshiftVersion'
      | cut -b-3
    register: ocp_version
    failed_when: ocp_version.stdout == 'nul' or ocp_version.stdout == ""
  rescue:
  - name: Fail because of a dependency issue
    fail:
      msg: |
        Failed to fetch OpenShift version. Please verify the failure message above and double check:
          1. that `KUBECONFIG` is properly set ({{ lookup('env', 'KUBECONFIG') }})
          2. that `oc` is available in the PATH
          3. that `jq` is available in the PATH
          4. that `oc` and `KUBECONFIG` are able to access the OpenShift cluster

- name: 'Store openshift_release={{ ocp_version.stdout }}'
  set_fact:
    openshift_release: "{{ ocp_version.stdout }}"
