- name: Create the sutest artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/artifacts-sutest/"
    state: directory
    mode: '0755'

- name: Capture the artifacts of the sutest cluster
  environment:
    KUBECONFIG: '{{ sut_cluster_kubeconfig }}'
  block:

  - name: Store OpenShift YAML version
    shell:
      oc version -oyaml > "{{ artifact_extra_logs_dir }}/artifacts-sutest/ocp_version.yml"
    ignore_errors: yes

  - name: Store the Cluster nodes
    shell:
      oc get nodes -oyaml > "{{ artifact_extra_logs_dir }}/artifacts-sutest/nodes.yaml"
    ignore_errors: yes

  - name: Get the description of the nodes
    shell:
      oc describe nodes
          > "{{ artifact_extra_logs_dir }}/artifacts-sutest/nodes.descr"
    ignore_errors: yes

  - name: Get the OpenShift Prometheus database
    include_role:
      name: cluster_prometheus_db
    vars:
      cluster_prometheus_db_mode: dump
      cluster_prometheus_db_dump_name_prefix: artifacts-sutest/prometheus_ocp
    when: capture_prom_db | bool

  - name: Get the RHODS Prometheus database
    include_role:
      name: cluster_prometheus_db
    vars:
      cluster_prometheus_db_mode: dump
      cluster_prometheus_db_label: deployment=prometheus
      cluster_prometheus_db_namespace: redhat-ods-monitoring
      cluster_prometheus_db_directory: /prometheus/data
      cluster_prometheus_db_dump_name_prefix: artifacts-sutest/prometheus_rhods
    when: capture_prom_db | bool
