---
- name: Get the name of an existing worker machineset
  shell:
    oc get machinesets -n openshift-machine-api -oname | grep worker | head -1
  register: oc_get_machinesets

- name: Create a temporary file for the original MachineSet
  ansible.builtin.tempfile:
    state: file
    suffix: .machineset.temp.yaml
  register: machineset_tempfile

- name: Create a temporary file for the GPU MachineSet
  ansible.builtin.tempfile:
    state: file
    suffix: .machineset.temp.yaml
  register: gpu_machineset_tempfile

- name: Store the MachineSet json definition in a temp file
  shell:
    oc get '{{ oc_get_machinesets.stdout }}' -n openshift-machine-api -o json > "{{ machineset_tempfile.path }}"

- name: "Transform the MachineSet to a GPU MachineSet (instance type: {{ gpu_instance_type }})"
  shell: >-
    {{ parse_machine_set }} {{ machineset_tempfile.path }} {{ gpu_instance_type }} > {{ gpu_machineset_tempfile.path }}

- name: Get the name of the new GPU MachineSet
  shell: cat '{{ gpu_machineset_tempfile.path }}' | jq -r .metadata.name
  register: gpu_machineset_name

- block:
  - name: Search if GPU MachineSet object already exists
    command: oc get 'machineset/{{ gpu_machineset_name.stdout }}' -n openshift-machine-api -oname
  rescue:
  - name: Create GPU MachineSet object
    command: oc create -f '{{ gpu_machineset_tempfile.path }}'

- block:
  - name: Wait for the GPU machine to be provisioned
    command:
      oc get machines --no-headers
        -l machines/cluster-api-machineset={{ gpu_machineset_name.stdout }}
        -o=jsonpath='{range .items[*]}{.status.phase}{end}'
        -n openshift-machine-api
    register: gpu_machine_state
    until:
    - gpu_machine_state.stdout == 'Running'
    retries: 1
    delay: 10
  rescue:
    - name: Capture more information about why the scale-up failed
      shell: |
        set -x;
        oc get 'machineset/{{ gpu_machineset_name.stdout }}' -n openshift-machine-api;
        oc get machines -n openshift-machine-api -l machines/cluster-api-machineset={{ gpu_machineset_name.stdout }};
        oc describe machines -n openshift-machine-api -l machines/cluster-api-machineset={{ gpu_machineset_name.stdout }};
    - name: Fail because of Machine scale-up failure
      fail:
        msg: Failing because of Machine scale-up failure
