---
- name: Get the name of an existing worker machineset
  command:
    oc get machines
      -n openshift-machine-api
      -l machine.openshift.io/cluster-api-machine-role=worker
      -o jsonpath='{range .items[*]}{.metadata.labels.machine\.openshift\.io/cluster-api-machineset}{"\n"}{end}'
  register: oc_get_machinesets
  failed_when: oc_get_machinesets.stdout == ""

- name: Create a temporary file for the original MachineSet
  ansible.builtin.tempfile:
    state: file
    suffix: .machineset.temp.yaml
  register: machineset_tempfile

- name: Create a temporary file for the new MachineSet
  ansible.builtin.tempfile:
    state: file
    suffix: .machineset.temp.yaml
  register: new_machineset_tempfile

- name: Store the MachineSet json definition in a temp file
  command:
    oc get 'machineset/{{ oc_get_machinesets.stdout_lines[0] }}' -n openshift-machine-api -o json
  register: oc_get_machinesets_json
  no_log: true # avoid overflowing stdout
- copy:
    dest: "{{ machineset_tempfile.path }}"
    content: "{{ oc_get_machinesets_json.stdout }}"

- name: "Update the MachineSet with the requested instance type ({{ machine_instance_type }})"
  command: "{{ parse_machine_set }} {{ machineset_tempfile.path }} {{ machine_instance_type }}"
  register: updated_machinesets_json
  no_log: true # avoid overflowing stdout
- copy:
    dest: "{{ new_machineset_tempfile.path }}"
    content: "{{ updated_machinesets_json.stdout }}"

- name: Get the name of the new MachineSet
  command: jq -r .metadata.name -- '{{ new_machineset_tempfile.path }}'
  register: new_machineset_name

- block:
  - name: Search if new MachineSet object already exists
    command: oc get 'machineset/{{ new_machineset_name.stdout }}' -n openshift-machine-api -oname
  rescue:
  - name: Create the new MachineSet object
    command: oc create -f '{{ new_machineset_tempfile.path }}'

- block:
  - name: Wait for the new Machine to be provisioned
    command:
      oc get machines --no-headers
        -l machine.openshift.io/cluster-api-machineset={{ new_machineset_name.stdout }}
        -o=jsonpath='{range .items[*]}{.status.phase}{end}'
        -n openshift-machine-api
    register: new_machine_state
    until:
    - new_machine_state.stdout == 'Running'
    retries: 45
    delay: 30

  - name: Wait for the new Node to be Ready
    command:
      oc get nodes --no-headers
        -l beta.kubernetes.io/instance-type={{ machine_instance_type }}
        -o=jsonpath='{..status.conditions[?(@.type=="Ready")].status}'
    register: new_node_ready
    until:
    - new_node_ready.stdout == 'True'
    retries: 45
    delay: 30

  rescue:
    - name: Capture more information about why the scale-up failed
      shell: |
        echo MachineSets;
        oc get 'machineset/{{ gpu_machineset_name.stdout }}' -n openshift-machine-api;
        echo GPU Machines;
        oc get machines -n openshift-machine-api -l 'machine.openshift.io/cluster-api-machineset={{ gpu_machineset_name.stdout }}';
        echo GPU Machines description;
        oc describe machines -n openshift-machine-api -l 'machine.openshift.io/cluster-api-machineset={{ gpu_machineset_name.stdout }}';
      ignore_errors: true

    - name: Fail because of Machine scale-up failure
      fail:
        msg: Failing because of Machine scale-up failure
