---
- block:
  - name: Check if requested machines exist
    shell: >
      oc get machines --no-headers -n openshift-machine-api -l machine.openshift.io/instance-type={{ machine_instance_type }}
      | grep Running
  - name: Found running machines with the requested machine type
    debug:
      msg: "Found running machines with type '{{ machine_instance_type }}', no need to scale-up"
  rescue:
  - name: Scale-up the cluster
    import_tasks: roles/openshift_node/tasks/create_machine.yml
    when: aws_scaleup_cluster == "yes"
