---
- name: Find a node with our NTO/TuneD fuse label
  command: oc get nodes -l "{{ tuned_module_fuse_label }}" -oname
  register: fuse_nodes

- name: Find a worker node to label for loading the fuse module with NTO/TuneD
  command: oc get nodes -l node-role.kubernetes.io/worker -oname
  when: not fuse_nodes.stdout
  register: worker_nodes

- name: Mark the node with our NTO/TuneD fuse label
  command: oc label "{{ worker_nodes.stdout_lines[0] }}" "{{ tuned_module_fuse_label }}="
  when: not fuse_nodes.stdout

- name: Apply NTO/TuneD fuse module profile manifest
  command: oc apply -f "{{ tuned_module_fuse }}"

- name: Apply the CI utils manifest
  command: oc apply -f "{{ nfd_operator_ci_utils }}"

- name: Authorize 'ns/nfd-operator-ci' Pods to access ns/nfd-operator-ci-utils images
  command:
    oc policy add-role-to-user
              system:image-puller system:serviceaccount:nfd-operator-ci:default
              --namespace=nfd-operator-ci-utils

- name: Apply the imagestream manifest
  command: oc apply -f "{{ nfd_operator_imagestream }}"

- name: Apply the image helper builder manifest
  command: oc apply -f "{{ nfd_operator_helper_image_builder }}"

- name: Wait for the helper image to be built
  block:
  - name: Wait for the helper image to be built
    command:
      oc get pod -lopenshift.io/build.name
                 --field-selector=status.phase=Succeeded
                 --no-headers
                 -oname
                 -n nfd-operator-ci-utils
    register: wait_helper_image
    until:
      - wait_helper_image.rc != 1
      - wait_helper_image.stdout != ""
    retries: 40
    delay: 30
  rescue:
  - name: Get info about the helper image build failure
    command: oc get pods -n nfd-operator-ci-utils
    failed_when: false

  - name: Get the logs of the helper image build failure
    command: oc logs bc/helper-image-builder -n nfd-operator-ci-utils
    failed_when: false

  - name: Get the description of the helper image build failure
    shell:
      oc describe build/helper-image-builder-1 -n nfd-operator-ci-utils
      > {{ artifact_extra_logs_dir }}/nfd_operator_helper_image_builder.log
    failed_when: false

  - name: Suggest how to retry the build
    debug: msg="To retry the build, run 'oc new-build bc/helper-image-builder -n nfd-operator-ci-utils'"

  - name: Fail because the custom operator image failed to build
    fail: msg="Fail because the custom operator image failed to build"


- name: Apply the operator image builder script manifest
  command: oc apply -f "{{ nfd_operator_image_builder_script }}"

- name: Prepare builder-dockercfg secret
  block:
  - name: Find the name of the builder-dockercfg secret
    shell: oc get secrets -oname -n nfd-operator-ci | cut -d/ -f2 | grep builder-dockercfg
    register: builder_secret_cmd

  - name: Set ansible variable for builder_secret
    set_fact:
      builder_secret: "{{ builder_secret_cmd.stdout }}"

  rescue:
  - name: Failed to find the builder-dockercfg secret
    fail: msg="No builder-dockercfg secret in the 'nfd-operator-ci' namespace ..."

- name: Create the operator image builder pod manifest
  template:
    src: "{{ nfd_operator_image_builder_pod }}"
    dest: "{{ artifact_extra_logs_dir }}/operator_image_builder_pod.yml"
    mode: 0400

- name: Delete the operator image builder pod, if any
  command: oc delete -f "{{ artifact_extra_logs_dir }}/operator_image_builder_pod.yml" --ignore-not-found=true

- name: Check if the operator image already exists
  command: oc get "imagestreamtag/nfd-operator-ci:{{ nfd_operator_image_tag }}" -n nfd-operator-ci
  failed_when: false
  register: has_operator_image

- name: Build the operator image
  when: has_operator_image.rc != 0
  block:
  - name: The operator image does not exist, build it
    debug: msg="The operator image does not exist, build it"

  - name: Apply the operator image builder pod manifest
    command: oc create -f "{{ artifact_extra_logs_dir }}/operator_image_builder_pod.yml"

  - block:
    - name: Wait for the operator image to be built
      command:
        oc get pod/operator-image-builder-pod
           --no-headers
           -ocustom-columns=phase:status.phase
           -n nfd-operator-ci
      register: wait_image_builder_pod
      until: "'Succeeded' in wait_image_builder_pod.stdout or 'Failed' in wait_image_builder_pod.stdout or 'Error' in wait_image_builder_pod.stdout"
      retries: 40
      delay: 30

    - name: Fail if the operator image failed to be built
      when: "'Failed' in wait_image_builder_pod.stdout or 'Error' in wait_image_builder_pod.stdout"
      fail: msg="The operator image failed to build"

    rescue:
    - name: Get info about the operator image build failure (debug)
      command: oc get pods -n nfd-operator-ci
      failed_when: false

    - name: Get the logs of image build failure (debug)
      command: oc logs pod/operator-image-builder-pod -n nfd-operator-ci
      failed_when: false

    - name: Fail because the operator image failed to build
      fail: msg="Fail because the operator image failed to build"
