apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ci-artifacts
  name: ci-artifacts
  namespace: ci-artifacts
spec:
  containers:
  - name: ci-artifacts
    command:
    - /bin/bash
    - -xc
    - "{{ local_ci_command }}"
    image: "image-registry.openshift-image-registry.svc:5000/ci-artifacts/ci-artifacts:{{ local_ci_image_tag }}" # set by `build.yaml` ansible script
    imagePullPolicy: Always
    env:
    - name: EXTRA_ANSIBLE_OPTS
      value: -e use_aws=no
    - name: KUBECONFIG
      value: /etc/kubeconfig/kubeconfig
    volumeMounts:
    - mountPath: /etc/kubeconfig
      name: kubeconfig-secret
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: kubeconfig-secret
    secret:
      secretName: kubeconfig-secret
