apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: fuse-for-buildah
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=An OpenShift profile to load 'fuse' module
      include=openshift-node
      [modules]
      fuse=+r
    name: openshift-fuse
  recommend:
  - match:
    - label: node.kubernetes.io/instance-type=g4dn.xlarge
    profile: "openshift-fuse"
    priority: 5
