---
- block:
  - include_tasks: roles/entitlement/tasks/deploy.yml
    when: entitlement_deploy == 'yes'
  - include_tasks: roles/entitlement/tasks/test_wait.yml
    when: entitlement_test == 'yes'
  rescue:
  - include_tasks: roles/entitlement/tasks/inspect.yml
  - name: Failing because of a previous error
    fail:
      msg: Failed because of a previous error

- include_tasks: roles/entitlement/tasks/inspect.yml
  when: entitlement_inspect == 'yes'

- include_tasks: roles/entitlement/tasks/undeploy.yml
  when: entitlement_undeploy == 'yes'
