skip_list:
  # Hide "wrong indentation: expected 4 but found 2 (indentation)"
  # until we find out how to properly configure it
  - 'yaml'
  # Do not force galaxy info in meta/main.yml
  - 'meta-no-info'
  # Hide "Commands should not change things if nothing needs doing"
  - 'no-changed-when'
  # Hide "Role name 'xxx_yyy' does not match ``^[a-z][a-z0-9_]+$`` pattern"
  - 'role-name'
