---
- name: Ensure that LOCAL_CI_COMMAND is set ('{{ local_ci_command }}')
  command: test "{{ local_ci_command }}"

- name: Apply the namespace manifest
  command: oc apply -f "{{ local_ci_namespace }}"

- name: Apply the imagestream manifest
  command: oc apply -f "{{ local_ci_imagestream }}"

- name: Delete the kubeconfig secret, if it exists
  command: oc delete secret -n ci-artifacts kubeconfig-secret --ignore-not-found=true

- name: Create kubeconfig secret
  command:
    oc create secret generic kubeconfig-secret
       -n ci-artifacts
       --from-file {{ lookup('env', 'KUBECONFIG') }}

- name: Search if the CI image exists
  command: oc get imagestreamtag -n ci-artifacts "ci-artifacts:{{ local_ci_image_tag }}" -oname
  register: has_ci_image

- name: Build the CI image
  when: has_ci_image.stdout != ""
  block:
  - name: Delete any old image builder manifest
    command: oc delete -f "{{ local_ci_image_builder }}" --ignore-not-found=true

  - name: Apply the CI artifacts image builder manifest
    shell:
      set -o pipefail;
      cat "{{ local_ci_image_builder }}" \
       | sed 's|{{ '{{' }} local_ci_git_repo {{ '}}' }}|{{ local_ci_git_repo }}|' \
       | sed 's|{{ '{{' }} local_ci_git_ref {{ '}}' }}|{{ local_ci_git_ref }}|' \
       | sed 's|{{ '{{' }} local_ci_image_tag {{ '}}' }}|{{ local_ci_image_tag }}|' \
       | oc apply -f-
    args:
      warn: false # don't warn about using sed here

  - name: Wait for the image to be built
    shell: oc logs -f bc/image-builder -n ci-artifacts > /dev/null

- name: Ensure that the image exists
  command: oc get imagestreamtag -n ci-artifacts "ci-artifacts:{{ local_ci_image_tag }}" -oname

- name: Delete any stalled CI execution Pod
  command: oc delete -f "{{ local_ci_execution_pod }}" --ignore-not-found=true

- name: Trigger the CI execution in a Pod
  shell:
    set -o pipefail;
    cat "{{ local_ci_execution_pod }}" \
      | sed 's|{{ '{{' }} local_ci_image_tag {{ '}}' }}|{{ local_ci_image_tag }}|' \
      | sed 's|{{ '{{' }} local_ci_command {{ '}}' }}|{{ local_ci_command }}|' \
      | oc apply -f-

- name: "Finished: the local CI execution has been launched."
  debug:
    msg: oc get pod/ci-artifacts -n ci-artifacts; oc logs -f pod/ci-artifacts -n ci-artifacts
