apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-burn-entrypoint
  namespace: default
data:
  entrypoint.sh: |-
    #!/bin/bash

    set -o pipefail
    set -o errexit
    set -o nounset

    set -x

    cp /gpu-burn-src/* .

    make

    echo ""
    echo "Running GPU Burn for ${GPU_BURN_TIME} seconds."
    time ./gpu_burn $GPU_BURN_TIME
