---
# Get NFD Operator instance status to ensure it's listed as "Available"
- name: Get the NFD Operator's 'nfd-instance' status to ensure its status is listed as 'Available'
  shell: |
    set -o pipefail;
    oc get nodefeaturediscoveries/nfd-instance -n '{{ nfd_operator_namespace }}' -o yaml | grep '{{ nfd_operator_available_status }}' -B 1 | grep status | cut -d'"' -f2
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_instance_ok
  failed_when: false

# If the instance status is NOT "Available", then fail
- name: If the NFD Operator's 'nfd-instance' status is NOT ' {{ nfd_operator_available_status }}', then trigger a fail
  fail: msg="The NFD Operator's 'nfd-instance' is not available."
  when: nfd_operator_instance_ok.stderr | length > 0
