apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "THEACCESSKEY",
      "secret_access_key": "3dc054ac0bc57d427de6358de9eb4734e09efa92f7ea7bace53515df8a32f02a",
      "endpoint_url": "http://minio.minio.svc:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }

