---
- name: Apply the CI utils manifest
  command: oc apply -f "{{ gpu_operator_ci_utils }}"

- name: Apply the namespace manifest
  command: oc apply -f "{{ gpu_operator_ci_namespace }}"

- name: Apply the imagestream manifest
  command: oc apply -f "{{ gpu_operator_ci_imagestream }}"

- name: Authorize 'ns/gpu-operator-ci' Pods to access ns/gpu-operator-ci-utils images
  command:
    oc policy add-role-to-user
              system:image-puller system:serviceaccount:gpu-operator-ci:default
              --namespace=gpu-operator-ci-utils

- block:
  - name: Find the name of the builder-dockercfg secret
    shell:
      set -o pipefail;
      oc get secrets -oname -n gpu-operator-ci | cut -d/ -f2 | grep builder-dockercfg
    register: builder_secret_cmd

  - name: Store the name of the secret in a variable
    set_fact:
      builder_secret: "{{ builder_secret_cmd.stdout }}"
  rescue:
  - name: Failed to find the builder-dockercfg secret
    fail: msg="No builder-dockercfg secret in the 'gpu-operator-ci' namespace ..."
