---
- name: "Check if the cluster already has a {{ machineset_instance_type }} machineset"
  shell:
    oc get machineset -n openshift-machine-api
    -o=jsonpath='{.items[?(@.spec.template.spec.providerSpec.value.instanceType=="{{ machineset_instance_type }}")].metadata.name}'
  register: cluster_has_machineset

- name: Cluster already has machineset with required type
  when: cluster_has_machineset.stdout
  debug: msg="Cluster already has a machineset with type '{{ machineset_instance_type }}', no need to create one"

- name: Create machineset with requested instance type, as the cluster does not have one
  when: not cluster_has_machineset.stdout
  block:
  - name: Derive the new machineset
    include_tasks: derive_machineset.yml
    