---
- name: Wait for OpenShift entitlement deployment
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    entitlement_test_and_wait: 'yes'
  roles:
  - role: entitlement_test_wait
