---
- name: Wait for a node to appear with an NVIDIA GPU PCI label
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
  - role: nfd_test_wait_gpu
    vars:
      nfd_wait_gpu_nodes: 'yes'
