# Create a machineset GPU enabled
- name: Scaling up an OCP GPU ready node
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - openshift_node
# Install and test GPU Operator from a custom commit
- name: Install and NVidia GPU operator From Given Commit
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: nv_gpu_install_from_commit
