---
# Install and test NFD
- name: CI Run OpenShift NFD
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: openshift_nfd
      when: test_nfd == "yes"

# Install and test SRO
- name: CI Run OpenShift SRO
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: openshift_sro
      when: test_sro == "yes"
