---
# Install and test Kubeflow (via Open Data Hub)
- name: CI Run Open Data Hub
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: openshift_odh
      when: test_odh == "yes"
