---
# Empty to use the latest version, or set to force a given version
gpu_operator_operatorhub_version: ""

# Channel to use in OperatorHub deployment subscription
gpu_operator_operatorhub_channel: ""
