---
# See if NV GPU Operator has been successfully installed
- name: Check if NVidia GPU operator has already been installed
  block:
    - name: CRD check - Ci mode
      shell: >
        oc get crds | grep clusterpolicies.nvidia.com
      register: nv_ci_crd_check
      until:
      - nv_ci_crd_check.rc == 0
      retries: 10
      delay: 10
    - name: cuda vector add validation status
      shell: |
        CUDA_VECTORADD_STATE=$(oc get pods --field-selector=status.phase=Succeeded -n gpu-operator-resources --no-headers 2> /dev/null | wc -l)
        exec test $CUDA_VECTORADD_STATE -eq 2
      register: nv_ci_cuda_validation_check
      until:
      - nv_ci_cuda_validation_check.rc == 0
      retries: 15
      delay: 60
  always:
    - name: capture GPU Pods states
      command: oc get pods -owide -n gpu-operator-resources
      ignore_errors: true
    - name: capture Pod images
      command: |
        oc get pods -n gpu-operator-resources -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}'
      ignore_errors: true
    - name: capture GPU Nodes states
      command: oc describe node -lnvidia.com/gpu.present=true
      ignore_errors: true
