- name: Create the namespace for the NFD Operator
  command: oc apply -f "{{ nfd_operator_namespace }}"

- name: Create the OperatorGroup object
  block:
    - name: apply operatorGroup manifest
      command: oc apply -f "{{ nfd_operator_operatorgroup }}"
      register: test_operatorgroup
  rescue:
    - name: Failed when creating the OperatorGroup object for the NFD Operator
      fail:
        msg: "{{ test_operatorgroup }}"

- name: Create the OperatorHub subscription for the NFD Operator
  block:
    - name: "apply operatorhub subscription manifest (nfd_channel = {{ nfd_channel }})"
      shell: sed 's|{{ '{{' }} nfd_channel {{ '}}' }}|{{ nfd_channel }}|' "{{ nfd_operator_operatorhub_sub }}" \
           | oc apply -f-
      register: nfd_operatorhub_sub
      args:
        warn: false # don't warn about using sed here
  rescue:
    - name: Failed when creating the test operatorHub subscription for the NFD Operator
      fail:
        msg: "{{ nfd_operatorhub_sub }}"

- name: Create the NodeFeatureDiscovery CR for the NFD Operator
  block:
    - name: apply NodeFeatureDiscovery manifest
      command: oc apply -f "{{ nfd_operator_crd }}"
      register: nfd_cr
      until: nfd_cr.rc != 1
      retries: 20
      delay: 15
  rescue:
    - name: Inspect NFD subscription
      command: oc describe subscriptions/nfd -n openshift-nfd
      ignore_errors: true
    - name: Failed when creating the test clusterpolicy CR for the GPU Operator
      fail:
        msg: "{{ nfd_cr }}"
