- name: Create the namespace for the GPU Operator
  command: oc apply -f "{{ gpu_operator_namespace }}"

- name: Create the OperatorHub subscription for the GPU Operator
  command: oc apply -f "{{ gpu_operator_operatorhub_sub }}"

- name: Create the clusterPolicy CRD for the GPU Operator
  command: oc apply -f "{{ gpu_operator_crd }}"
  register: test_clusterpolicy_cr
  until: test_clusterpolicy_cr.rc != 1
  retries: 20
  delay: 15
