- name: Create the namespace for the NFD Operator
  command: oc apply -f "{{ nfd_operator_namespace }}"

- name: Create the OperatorGroup object
  command: oc apply -f "{{ nfd_operator_operatorgroup }}"

- name: "Create the OperatorHub subscription for the NFD Operator (nfd_channel = {{ nfd_channel }})"
  shell: sed 's|{{ '{{' }} nfd_channel {{ '}}' }}|{{ nfd_channel }}|' "{{ nfd_operator_operatorhub_sub }}" \
       | oc apply -f-
  args:
    warn: false # don't warn about using sed here

- name: Create the NodeFeatureDiscovery CR for the NFD Operator
  block:
    - name: apply NodeFeatureDiscovery manifest
      command: oc apply -f "{{ nfd_operator_cr }}"
      register: nfd_cr
      until: nfd_cr.rc != 1
      retries: 20
      delay: 15
  rescue:
    - name: Inspect NFD subscription
      command: oc describe subscriptions/nfd -n openshift-nfd
      ignore_errors: true
    - name: Failed when creating the test clusterpolicy CR for the GPU Operator
      fail:
        msg: "{{ nfd_cr }}"
