- block:
  - name: Install NFD-operator from OperatorHub
    include_tasks: roles/nv_gpu/tasks/install_nfd.yml
    when: install_nfd_operator_from_hub == "yes"

  - name: Install GPU-operator from OperatorHub
    include_tasks: roles/nv_gpu/tasks/install_nv.yml
    when: install_gpu_operator_from_hub == "yes"

  - include_tasks: ci_checks.yml
    when: user_mode == 'ci'

  rescue:
  - include_tasks: verbose_failure.yml
  - name: Failing because of a previous error
    fail:
      msg: "Failing because of a previous error"

- name: Uninstall GPU-operator from OperatorHub
  include_tasks: uninstall_nv.yml
  when: undeploy_gpu_operator == "yes"
