- block:
  - name: Install NFD-operator from OperatorHub
    include_tasks: roles/nv_gpu/tasks/install_nfd.yml
    when: install_nfd_operator_from_hub == "yes"

  - name: Wait for NFD-labeled GPU nodes to appear
    include_tasks: roles/nv_gpu/tasks/test_nfd_gpu.yml
    when: nfd_test_gpu_nodes == "yes"

  - name: Install GPU-operator from OperatorHub
    include_tasks: roles/nv_gpu/tasks/install_nv.yml
    when: install_gpu_operator_from_hub == "yes"

  - name: Check if NVidia GPU operator has already been installed
    block:
    - include_tasks: ci_checks.yml
      when: user_mode == 'ci'

    always:
    - name: capture GPU Pods states
      shell: "oc get pods -owide -n gpu-operator-resources > {{ artifact_extra_logs_dir }}/gpu_pods_list"
      ignore_errors: true
      when: artifact_extra_logs_dir | default('', true) | trim != ''
    - name: capture GPU Pod images
      shell:
        oc get pods -n gpu-operator-resources
          -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}'
          > {{ artifact_extra_logs_dir }}/gpu_pods_image
      ignore_errors: true
      when: artifact_extra_logs_dir | default('', true) | trim != ''
    - name: capture Operator Pod image
      shell:
        oc get pods -n openshift-operators
          -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}'
          > {{ artifact_extra_logs_dir }}/operator_pods_image
      ignore_errors: true
      when: artifact_extra_logs_dir | default('', true) | trim != ''
    - name: capture GPU Nodes states
      shell: "oc describe node -lnvidia.com/gpu.present=true > {{ artifact_extra_logs_dir }}/gpu_nodes_description"
      ignore_errors: true
      when: artifact_extra_logs_dir | default('', true) | trim != ''

  rescue:
  - include_tasks: verbose_failure.yml
  - name: Failing because of a previous error
    fail:
      msg: "Failing because of a previous error"

- name: Uninstall GPU-operator from OperatorHub
  include_tasks: uninstall_nv.yml
  when: undeploy_gpu_operator == "yes"

- name: Uninstall NFD-operator from OperatorHub
  include_tasks: uninstall_nfd.yml
  when: undeploy_nfd_operator == "yes"
