---
- name: Delete the OperatorHub subscription for the NFD Operator
  command: oc delete -f "{{ nfd_operator_operatorhub_sub }}" --ignore-not-found=true

- name: Get the name of the NFD Operator ClusterServiceVersion
  shell: oc get ClusterServiceVersion -n openshift-nfd -oname | grep /nfd
  register: operator_csv_name
  ignore_errors: true

- name: Delete the ClusterServiceVersion of the NFD Operator
  with_items: "{{ operator_csv_name.stdout_lines }}"
  command: oc delete "{{ item }}" -n openshift-operators --ignore-not-found=true
  when: operator_csv_name.rc == 0
  ignore_errors: true

- name: Delete the NodeFeatureDiscovery CR of the NFD Operator
  command: oc delete -f "{{ nfd_operator_cr }}" --ignore-not-found=true

- name: Delete the CRD of the NFD Operator
  command: oc delete crd nodefeaturediscoveries.nfd.openshift.io --ignore-not-found=true

- name: Delete the namespace of the GPU Operator
  command: oc delete -f "{{ nfd_operator_namespace }}" --ignore-not-found=true
