---
- name: Get the name of the GPU Operator ClusterPolicy CR
  command: oc get ClusterPolicy -oname
  register: gpu_operator_cr_name
  ignore_errors: true

- name: Delete the clusterPolicy CR of the GPU Operator
  command: oc delete "{{ gpu_operator_cr_name.stdout }}"
  when: gpu_operator_cr_name.rc == 0
  ignore_errors: true

- name: Delete the OperatorHub subscription for the GPU Operator
  command: oc delete Subscription/gpu-operator-certified -n openshift-operators
  ignore_errors: true

- name: Get the name of the GPU Operator ClusterServiceVersion
  shell: oc get ClusterServiceVersion -n openshift-operators -oname | grep gpu-operator
  register: operator_csv_name
  ignore_errors: true

- name: Delete the ClusterServiceVersion of the GPU Operator
  with_items: "{{ operator_csv_name.stdout_lines }}"
  shell: "oc delete {{ item }} -n openshift-operators"
  ignore_errors: true
  when: operator_csv_name.rc == 0

- name: Delete the CRD of the GPU Operator
  command: oc delete crd clusterpolicies.nvidia.com
  ignore_errors: true

- name: Delete the namespace of the GPU Operator
  command: oc delete -f "{{ gpu_operator_namespace }}"
  ignore_errors: true
