name: Generate documentation on master branch push
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Generate the documentation 🔧
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html # The folder the action should deploy.

    - name: Generate the MultiVersion documentation
      run: cd docs; make gh-action_multiversion # currently not doing anything
