name: Test documentation generation on master branch PR
on:
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Generate the documentation 🔧
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs
