---
- name: Git checkout
  ansible.builtin.git:
    repo: "{{ sro_git_repo }}"
    dest: /tmp/special-resource-operator
    version: "{{ sro_git_ref }}"
    force: yes

- name: Deploy the custom version of the special resource operator
  shell: 
    make undeploy NAMESPACE="openshift-special-resource-operator"
        > {{ artifact_extra_logs_dir }}/sro_undeploy_custom.log 2>&1
  args:
    chdir: /tmp/special-resource-operator
